package com.dgs.data.domain;


// Generated Dec 6, 2015 3:57:28 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Coursemaster generated by hbm2java
 */
@Entity
@Table(name = "coursemaster", catalog = "dgs")
public class Coursemaster implements java.io.Serializable {

	private String courseId;
	private String courseName;
	private Set professorcoursemappings = new HashSet(0);
	private Set studentmappings = new HashSet(0);

	public Coursemaster() {
	}

	public Coursemaster(String courseId, String courseName) {
		this.courseId = courseId;
		this.courseName = courseName;
	}

	public Coursemaster(String courseId, String courseName,
			Set professorcoursemappings, Set studentmappings) {
		this.courseId = courseId;
		this.courseName = courseName;
		this.professorcoursemappings = professorcoursemappings;
		this.studentmappings = studentmappings;
	}

	@Id
	@Column(name = "courseId", unique = true, nullable = false, length = 50)
	public String getCourseId() {
		return this.courseId;
	}

	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}

	@Column(name = "courseName", nullable = false, length = 500)
	public String getCourseName() {
		return this.courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "coursemaster")
	public Set getProfessorcoursemappings() {
		return this.professorcoursemappings;
	}

	public void setProfessorcoursemappings(Set professorcoursemappings) {
		this.professorcoursemappings = professorcoursemappings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "coursemaster")
	public Set getStudentmappings() {
		return this.studentmappings;
	}

	public void setStudentmappings(Set studentmappings) {
		this.studentmappings = studentmappings;
	}

}
