package com.dgs.data.domain;


// Generated Dec 6, 2015 3:57:28 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Grademaster generated by hbm2java
 */
@Entity
@Table(name = "grademaster", catalog = "dgs")
public class Grademaster implements java.io.Serializable {

	private String gradeId;
	private String percentageRange;
	private Set studentmappings = new HashSet(0);

	public Grademaster() {
	}

	public Grademaster(String gradeId, String percentageRange) {
		this.gradeId = gradeId;
		this.percentageRange = percentageRange;
	}

	public Grademaster(String gradeId, String percentageRange,
			Set studentmappings) {
		this.gradeId = gradeId;
		this.percentageRange = percentageRange;
		this.studentmappings = studentmappings;
	}

	@Id
	@Column(name = "gradeId", unique = true, nullable = false, length = 10)
	public String getGradeId() {
		return this.gradeId;
	}

	public void setGradeId(String gradeId) {
		this.gradeId = gradeId;
	}

	@Column(name = "percentageRange", nullable = false, length = 20)
	public String getPercentageRange() {
		return this.percentageRange;
	}

	public void setPercentageRange(String percentageRange) {
		this.percentageRange = percentageRange;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grademaster")
	public Set getStudentmappings() {
		return this.studentmappings;
	}

	public void setStudentmappings(Set studentmappings) {
		this.studentmappings = studentmappings;
	}

}
