package com.dgs.data.domain;


// Generated Dec 6, 2015 3:57:28 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Professorcoursemapping generated by hbm2java
 */
@Entity
@Table(name = "professorcoursemapping", catalog = "dgs")
public class Professorcoursemapping implements java.io.Serializable {

	private Integer professorMappingId;
	private Coursemaster coursemaster;
	private Usermaster usermaster;

	public Professorcoursemapping() {
	}

	public Professorcoursemapping(Coursemaster coursemaster,
			Usermaster usermaster) {
		this.coursemaster = coursemaster;
		this.usermaster = usermaster;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "professorMappingId", unique = true, nullable = false)
	public Integer getProfessorMappingId() {
		return this.professorMappingId;
	}

	public void setProfessorMappingId(Integer professorMappingId) {
		this.professorMappingId = professorMappingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "courseId", nullable = false)
	public Coursemaster getCoursemaster() {
		return this.coursemaster;
	}

	public void setCoursemaster(Coursemaster coursemaster) {
		this.coursemaster = coursemaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId", nullable = false)
	public Usermaster getUsermaster() {
		return this.usermaster;
	}

	public void setUsermaster(Usermaster usermaster) {
		this.usermaster = usermaster;
	}

}
