package com.dgs.data.domain;


// Generated Dec 6, 2015 3:57:28 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Studentmapping generated by hbm2java
 */
@Entity
@Table(name = "studentmapping", catalog = "dgs")
public class Studentmapping implements java.io.Serializable {

	private Integer studentMappingId;
	private Coursemaster coursemaster;
	private Usermaster usermaster;
	private Grademaster grademaster;

	public Studentmapping() {
	}

	public Studentmapping(Coursemaster coursemaster, Usermaster usermaster,
			Grademaster grademaster) {
		this.coursemaster = coursemaster;
		this.usermaster = usermaster;
		this.grademaster = grademaster;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "studentMappingId", unique = true, nullable = false)
	public Integer getStudentMappingId() {
		return this.studentMappingId;
	}

	public void setStudentMappingId(Integer studentMappingId) {
		this.studentMappingId = studentMappingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "courseId", nullable = false)
	public Coursemaster getCoursemaster() {
		return this.coursemaster;
	}

	public void setCoursemaster(Coursemaster coursemaster) {
		this.coursemaster = coursemaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId", nullable = false)
	public Usermaster getUsermaster() {
		return this.usermaster;
	}

	public void setUsermaster(Usermaster usermaster) {
		this.usermaster = usermaster;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "gradeId", nullable = false)
	public Grademaster getGrademaster() {
		return this.grademaster;
	}

	public void setGrademaster(Grademaster grademaster) {
		this.grademaster = grademaster;
	}

}
